/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "643ede69216c073c2dd497c382577dc9fde36b3e"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
